"""
Evolution Infrastructure - Memory-Aware Darwin Integration + Multi-Agent Evolve

This module provides memory-backed evolution capabilities for Genesis agents,
enabling cross-business and cross-agent learning through persistent memory.

Key Components:
- MemoryAwareDarwin: Main evolution orchestrator with memory integration
- EvolutionPattern: Proven patterns stored in memory for reuse
- EvolutionResult: Evolution run results with memory metrics
- SolverAgent: Multi-Agent Evolve Solver for co-evolution (NEW: arXiv:2510.23595)
- SolverConfig: Configuration for Solver agent behavior
- SolverTrajectory: Solution trajectory generated by Solver
- VerifierFeedback: Feedback from Verifier to Solver
- VerifierAgent: Multi-Agent Evolve Verifier for adversarial validation (NEW: arXiv:2510.23595)
- VerifierConfig: Configuration for Verifier agent behavior
- VerificationResult: Multi-criteria verification result with feedback

Usage (Memory-Aware Darwin):
    from infrastructure.evolution import MemoryAwareDarwin
    from infrastructure.langgraph_store import get_store

    # Initialize with memory
    memory_darwin = MemoryAwareDarwin(
        agent_type="qa_agent",
        memory_store=get_store(),
        capability_tags=["code_analysis", "validation"]
    )

    # Run evolution
    result = await memory_darwin.evolve_with_memory(
        task={"type": "validation", "description": "..."},
        business_id="saas_001"
    )

    # Result shows 10%+ improvement over isolated mode
    print(f"Score: {result.final_score}, Improvement: {result.improvement_over_baseline}")

Usage (Multi-Agent Evolve Solver):
    from infrastructure.evolution import SolverAgent, SolverConfig

    # Initialize Solver with custom config
    config = SolverConfig(
        diversity_weight=0.3,
        quality_weight=0.5,
        verifier_weight=0.2,
        num_trajectories=5
    )
    solver = SolverAgent("qa_agent", config=config)

    # Generate solution trajectories
    task = {"type": "code_generation", "description": "Implement binary search"}
    trajectories = await solver.generate_trajectories(task)

    # Compute reward for co-evolution
    reward = solver.compute_solver_reward(
        trajectory=trajectories[0],
        benchmark_score=0.9,
        verifier_score=0.85
    )

Usage (Multi-Agent Evolve Verifier):
    from infrastructure.evolution import VerifierAgent, VerifierConfig

    # Initialize Verifier with custom config
    config = VerifierConfig(
        correctness_weight=0.4,
        quality_weight=0.3,
        robustness_weight=0.2,
        generalization_weight=0.1,
        num_edge_cases=5
    )
    verifier = VerifierAgent("qa_agent", config=config)

    # Verify Solver trajectory
    task = {"type": "code_generation", "description": "Implement binary search"}
    trajectory = trajectories[0]  # From Solver
    result = await verifier.verify_trajectory(trajectory, task)

    # Analyze verification results
    print(f"Score: {result.verification_score:.3f}")
    print(f"Shortcuts: {result.shortcuts_detected}")
    print(f"Feedback: {result.feedback}")

    # Compute Verifier reward for co-evolution
    reward = verifier.compute_verifier_reward(
        verification_score=result.verification_score,
        previous_verification_score=0.8
    )
"""

from infrastructure.evolution.memory_aware_darwin import (
    MemoryAwareDarwin,
    EvolutionPattern,
    EvolutionResult
)

from infrastructure.evolution.solver_agent import (
    SolverAgent,
    SolverConfig,
    SolverTrajectory,
    VerifierFeedback,
    get_solver_agent
)

from infrastructure.evolution.verifier_agent import (
    VerifierAgent,
    VerifierConfig,
    VerificationResult,
    get_verifier_agent
)

__all__ = [
    # Memory-Aware Darwin
    "MemoryAwareDarwin",
    "EvolutionPattern",
    "EvolutionResult",
    # Multi-Agent Evolve (Solver)
    "SolverAgent",
    "SolverConfig",
    "SolverTrajectory",
    "VerifierFeedback",
    "get_solver_agent",
    # Multi-Agent Evolve (Verifier)
    "VerifierAgent",
    "VerifierConfig",
    "VerificationResult",
    "get_verifier_agent"
]
